md "Todos os paises"
cd "Todos os paises"
md "Argentina" "Aruba" "Bolivia" "Bonaire" "Brasil" "Chile" "Colombia" "Curacao" "Equador" "Guiana" "Guiana Francesa" "Ilhas Malvinas" "Ilhas Georgia do Sul" "Paraguai" "Peru" "Suriname" "Uruguai" "Venezuela"
cd "Brasil"
md "Acre" "Alagoas" "Amapa" "Bahia" "Ceara" "Espirito Santo" "Goias" "Maranhao" "Mato Grosso" "Mato Grosso do Sul" "Minas Gerais" "Para" "Paraiba" "Parana" "Pernambuco" "Piaui" "Rio de Janeiro" "Rio Grande do Norte" "Rio Grande do Sul" "Rondonia" "Roraima" "Santa Catarina" "Sao Paulo" "Sergipe" "Tocantins" "Distrito Federal"